:compat-mode:
= Lab 7 - Leveraging Spring Cloud Connectors for Service Binding

In this lab we'll bind our RESTful web service from link:../lab_06/lab_06.adoc[Lab 6] to a MySQL database and leverage Spring Cloud Connectors to easily connect to it.

NOTE: The completed code for this lab can be found at `$COURSE_HOME/session_04/lab_07/complete/cities`.

== Using Spring Cloud Connectors

. Change to the lab directory (the initial state for this lab is the same as the completed state for link:../lab_06/lab_06.adoc[Lab 6], so you can choose to continue with that project if you like footnote:[However, please use the copy of `import.sql` found in the `lab_06/initial/cities/src/main/resources` directory. It is a subset of the original dataset, which is necessary because we are using a free tier database service.]):
+
----
$ cd $COURSE_HOME/session_04/lab_07/initial/cities
----

. At present we're still using the in-memory database. Let's connect to a MySQL database service.
From the CLI, let's _create_ a developer ClearDB MySQL Database service instance:
+
[source,bash]
----
$ cf create-service cleardb spark cities-db
Creating service cities-db...
OK
----
+
Or with FNTS or PEZ:
+
----
$ cf create-service p-mysql 100mb-dev cities-db
...
----

. Next add the service to your application manifest, which will _bind_ the service to our application on the next push. We'll also add an environment variable to switch on the ``cloud'' profile,
+
[source,yml]
----
---
applications:
- name: cities
  memory: 512M
  instances: 1
  path: build/libs/cities-0.0.1-SNAPSHOT.jar
  timeout: 180
  services:                        # Add
  - cities-db                      # these
  env:                             # four
    SPRING_PROFILES_ACTIVE: cloud  # lines
----
+
You can also accomplish the service binding by explicitly binding the service at the command-line:
+
[source,bash]
----
$ cf bind-service cities cities-db
Binding service cities-db to app cities...
OK
----

. Next we'll add Spring Cloud and MySQL dependencies to our Gradle build. Comment or remove the +hsqldb+ line and add the following in the +dependencies+ section:
+
[source,groovy]
----
dependencies {
    // ....
    //runtime("org.hsqldb:hsqldb")
    compile("org.springframework.cloud:spring-cloud-spring-service-connector:1.1.0.RELEASE")
    compile("org.springframework.cloud:spring-cloud-cloudfoundry-connector:1.1.0.RELEASE")
    runtime("org.mariadb.jdbc:mariadb-java-client:1.1.7")
}
----
+
__IMPORTANT__: Since we've added new dependencies, re-run +./gradlew idea+ or +./gradlew eclipse+ to have them added to the IDE classpath.

. Next, let's create the package +org.example.cities.config+ and create in that package the class +CloudDataSourceConfig+. Add the following code:
+
[source,java]
----
import org.springframework.cloud.config.java.AbstractCloudConfig;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

@Profile("cloud")
@Configuration
public class CloudDataSourceConfig extends AbstractCloudConfig {
    @Bean
    public DataSource dataSource() {
        return connectionFactory().dataSource();
    }
}
----
+
As before, have the IDE import the appropriate dependencies.
+
The +@Profile+ annotation will cause this class (which becomes Spring configuration when annotated as +@Configuration+) to be added to the configuration set because of the +SPRING_PROFILES_ACTIVE+ environment variable we added earlier. You can still run the application locally (with the default profile) using the embedded database.
+
With this code, Spring Cloud will detect a bound service that is compatible with +DataSource+, read the credentials, and then create a +DataSource+ as appropriate (it will throw an exception otherwise).

. Add the following to +src/main/resources/application.properties+ to cause Hibernate to create the database schema and import data at startup. This is done automatically for embedded databases, not for custom ++DataSource++s. Other Hibernate native properties can be set in a similar fashion:
+
[source,java]
----
spring.jpa.hibernate.ddl-auto=create
----

. Build the application:
+
[source,bash]
----
$ ./gradlew assemble
----

. Re-push the application:
+
[source,bash]
----
$ cf push
----

. Take a look at the +env+ endpoint again to see the service bound in +VCAP_SERVICES+:
+
[source,bash]
----
$ curl http://cities-crouse-penance.cfapps.io/env
...
VCAP_SERVICES: "{"cleardb":[{"name":"cities-db","label":"cleardb","tags":["Cloud Databases","Data Stores","Developer Tools","Web-based","Data Store","Single Sign-On","Buyable","relational","mysql","Certified Applications"],"plan":"spark","credentials":{"jdbcUrl":"jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/ad_5a3615550687288?user=ba02b32c3a2a8b&password=1e5c4921","uri":"mysql://ba02b32c3a2a8b:1e5c4921@us-cdbr-iron-east-03.cleardb.net:3306/ad_5a3615550687288?reconnect=true","name":"ad_5a3615550687288","hostname":"us-cdbr-iron-east-03.cleardb.net","port":"3306","username":"ba02b32c3a2a8b","password":"1e5c4921"}}]}",
...
----
The application is now running against a MySQL database.

== Customizing the +DataSource+

. You can customize the database connection that Spring Cloud creates with a few lines of code. Change the +dataSource+ method in +CloudDataSourceConfig+ to add some pooling and connection configuration:
+
[source,java]
----
//additional imports
import org.springframework.cloud.service.PooledServiceConnectorConfig;
import org.springframework.cloud.service.relational.DataSourceConfig;

//changed dataSource method
@Bean
public DataSource dataSource() {
    PooledServiceConnectorConfig.PoolConfig poolConfig =
            new PooledServiceConnectorConfig.PoolConfig(5, 200);

    DataSourceConfig.ConnectionConfig connectionConfig =
            new DataSourceConfig.ConnectionConfig("characterEncoding=UTF-8");
    DataSourceConfig serviceConfig = new DataSourceConfig(poolConfig, connectionConfig);

    return connectionFactory().dataSource("cities-db", serviceConfig);
}
----

. Build the application:
+
[source,bash]
----
$ ./gradlew assemble
----

. Re-push the application:
+
[source,bash]
----
$ cf push
----

== Clean Up

Issue the following commands to delete the cities application and its database.

. Delete the `cities` application:
+
----
$ cf d cities

Really delete the app cities?> y
Deleting app cities in org oreilly-class / space instructor as cbusch@pivotal.io...
'OK
----

. Delete the `cities-db` service:
+
----
$ cf ds cities-db

Really delete the service cities-db?> y
Deleting service cf-scale-boot-logs in org oreilly-class / space instructor as cbusch@pivotal.io...
OK
----

link:/README.md#course-materials[Course Materials home] | link:/session_05/lab_08/lab_08.adoc[Lab 8 - Binding to Spring Cloud Services]
